name: ml-101-env
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.10.15
  - certifi=2018.10.15
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=18.1
  - python=3.6.6
  - readline=7.0
  - setuptools=39.1.0
  - sqlite=3.25.2
  - tk=8.6.8
  - wheel=0.32.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.6.1
    - actionlib==1.11.13
    - alabaster==0.7.12
    - angles==1.9.11
    - astor==0.7.1
    - babel==2.6.0
    - bondpy==1.8.3
    - camera-calibration==1.12.23
    - camera-calibration-parsers==1.11.13
    - catkin==0.7.14
    - chardet==3.0.4
    - cv-bridge==1.12.8
    - diagnostic-analysis==1.9.3
    - diagnostic-common-diagnostics==1.9.3
    - diagnostic-updater==1.9.3
    - docutils==0.14
    - dynamic-reconfigure==1.5.50
    - gast==0.2.0
    - gazebo-plugins==2.5.17
    - gazebo-ros==2.5.17
    - gencpp==0.6.0
    - geneus==2.2.6
    - genlisp==0.4.16
    - genmsg==0.5.11
    - gennodejs==2.0.1
    - genpy==0.6.7
    - grpcio==1.16.0
    - h5py==2.8.0
    - idna==2.7
    - image-geometry==1.12.8
    - imagesize==1.1.0
    - interactive-markers==1.11.4
    - jinja2==2.10
    - keras==2.2.4
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - laser-geometry==1.6.4
    - markdown==3.0.1
    - markupsafe==1.0
    - message-filters==1.12.14
    - numpy==1.15.3
    - packaging==18.0
    - pluginlib==1.11.3
    - protobuf==3.6.1
    - pygments==2.2.0
    - pyparsing==2.2.2
    - python-qt-binding==0.3.4
    - pytz==2018.6
    - pyyaml==3.13
    - qt-dotgraph==0.3.11
    - qt-gui==0.3.11
    - qt-gui-cpp==0.3.11
    - qt-gui-py-common==0.3.11
    - requests==2.20.0
    - resource-retriever==1.12.4
    - rosbag==1.12.14
    - rosboost-cfg==1.14.4
    - rosclean==1.14.4
    - roscreate==1.14.4
    - rosgraph==1.12.14
    - roslaunch==1.12.14
    - roslib==1.14.4
    - roslint==0.11.0
    - roslz4==1.12.14
    - rosmake==1.14.4
    - rosmaster==1.12.14
    - rosmsg==1.12.14
    - rosnode==1.12.14
    - rosparam==1.12.14
    - rospy==1.12.14
    - rosservice==1.12.14
    - rostest==1.12.14
    - rostopic==1.12.14
    - rosunit==1.14.4
    - roswtf==1.12.14
    - rqt-action==0.4.9
    - rqt-bag==0.4.12
    - rqt-bag-plugins==0.4.12
    - rqt-console==0.4.8
    - rqt-dep==0.4.9
    - rqt-graph==0.4.9
    - rqt-gui==0.5.0
    - rqt-gui-py==0.5.0
    - rqt-image-view==0.4.13
    - rqt-launch==0.4.8
    - rqt-logger-level==0.4.8
    - rqt-moveit==0.5.7
    - rqt-msg==0.4.8
    - rqt-nav-view==0.5.7
    - rqt-plot==0.4.8
    - rqt-pose-view==0.5.8
    - rqt-publisher==0.4.8
    - rqt-py-common==0.5.0
    - rqt-py-console==0.4.8
    - rqt-reconfigure==0.4.10
    - rqt-robot-dashboard==0.5.7
    - rqt-robot-monitor==0.5.8
    - rqt-robot-steering==0.5.9
    - rqt-runtime-monitor==0.5.7
    - rqt-rviz==0.5.10
    - rqt-service-caller==0.4.8
    - rqt-shell==0.4.9
    - rqt-srv==0.4.8
    - rqt-tf-tree==0.5.8
    - rqt-top==0.4.8
    - rqt-topic==0.4.10
    - rqt-web==0.4.8
    - rviz==1.12.16
    - scipy==1.1.0
    - sensor-msgs==1.12.6
    - six==1.11.0
    - smach==2.0.1
    - smach-ros==2.0.1
    - smclib==1.8.3
    - snowballstemmer==1.2.1
    - sphinx==1.8.1
    - sphinxcontrib-websupport==1.1.0
    - tensorboard==1.11.0
    - tensorflow==1.11.0
    - termcolor==1.1.0
    - tf==1.11.9
    - tf-conversions==1.11.9
    - tf2-geometry-msgs==0.5.18
    - tf2-kdl==0.5.18
    - tf2-py==0.5.18
    - tf2-ros==0.5.18
    - topic-tools==1.12.14
    - urllib3==1.24
    - werkzeug==0.14.1
    - xacro==1.11.3

